//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserProfileApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public short CVV { get; set; }
        public short ExpiryMonth { get; set; }
        public short ExpiryYear { get; set; }
        public string NameOnCard { get; set; }
    
        public virtual User User { get; set; }
    }
}
